# Generated by Django 5.0.3 on 2024-03-25 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="car_owner",
        ),
    ]
