# Generated by Django 5.0.3 on 2024-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0002_remove_car_car_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="hours",
            field=models.PositiveIntegerField(default=24),
        ),
    ]
