# Generated by Django 5.0.3 on 2024-03-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0003_car_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="hours",
            field=models.PositiveIntegerField(),
        ),
    ]
