# Generated by Django 5.0.3 on 2024-03-25 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("car_rental", "0004_alter_car_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="hours",
        ),
    ]
