# Generated by Django 5.0.3 on 2024-03-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PATH", "0006_rename_customeruser_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="car_photos/"),
        ),
    ]
