# Generated by Django 5.0.3 on 2024-03-26 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='createParcelRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('source', models.TextField()),
                ('destination', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqstr', models.CharField(blank=True, max_length=255, null=True)),
                ('recvr', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Requested', max_length=50)),
                ('msg', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('recipient', models.CharField(max_length=150)),
                ('source_city', models.TextField(blank=True, null=True)),
                ('destination_city', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_delivered', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='parcel_service')),
                ('is_accepted', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Requested', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ride_id', models.IntegerField(blank=True, null=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
